---
- hosts: all
  become: yes
  tasks:
  - name: update packages
    apt:
      update_cache: true

- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
  tasks:
  - name: create nodeapp directory
    file:
      path: "{{ folderpath }}" 
      state: directory
      mode: 0755
  - name: Download node js package setup
    command: "get_url -sL https://deb.nodesource.com/setup_8.x -o {{folderpath}}/nodesource_setup.sh"
  - name: Execute downloaded shell script
    command: "sudo bash {{folderpath}}/nodesource_setup.sh"
  - name: Installing node js
    apt:
      name: nodejs
      state: present
    

